default_job = "check-all"

[jobs]

[jobs.run]
command = [
    "cargo", "run",
    "--bin", "fc-search",
    "--color", "always",
    "--",
    "--test",
    "--state-dir", "./test-state-dir"
]
need_stdout = true
watch = ["templates", "src"]
env.RUST_LOG = "fc_search=debug"

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests"]

[jobs.check]
command = [
	"cargo", "check",
	"--color", "always",
	"--features", "clipboard",
]
need_stdout = false
watch = ["benches"]

[jobs.test]
command = [
    "cargo", "test", "--color", "always",
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.clippy]
command = [
	"cargo", "clippy",
	"--color", "always",
	"--",
	"-A", "clippy::bool_to_int_with_if",
	"-A", "clippy::collapsible_else_if",
	"-A", "clippy::collapsible_if",
	"-A", "clippy::derive_partial_eq_without_eq",
	"-A", "clippy::len_without_is_empty",
	"-A", "clippy::get_first",
]
need_stdout = false
